library:
  source-dirs: src
tests:
  storm-codegen-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - storm-codegen
copyright: 2020 Nico Lehmann
maintainer: nlehmann@eng.ucsd.edu
dependencies:
  - unordered-containers
  - data-default
  - lens
  - hslogger
  - mtl
  - base >= 4.7 && < 5
  - containers
  - QuasiText
  - megaparsec
  - text
  - raw-strings-qq
  - fuzzyset
  - haskell-lsp
  - stm
name: storm-codegen
version: 0.1.0.0
extra-source-files:
  - README.md
  - ChangeLog.md
author: Nico Lehmann
github: nilehmann/storm-codegen
license: BSD3
executables:
  storm-codegen:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - storm-codegen
  storm-lsp:
    source-dirs: app
    main: Server.hs
    ghc-options:
      - -main-is Server
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - storm-codegen
description: Please see the README on GitHub at <https://github.com/nilehmann/storm-codegen#readme>
